"""Create the scores table.

Revision ID: 2794a51430ed
Revises: 35b9c4602f4e
Create Date: 2022-02-23 10:29:36.567110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2794a51430ed'
down_revision = '35b9c4602f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('teams_id', sa.Integer(), nullable=False),
    sa.Column('rounds_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rounds_id'], ['rounds.id'], ),
    sa.ForeignKeyConstraint(['teams_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
