"""Relationship between prize and round.

Revision ID: 90a8da5fc6a7
Revises: 950cac571497
Create Date: 2022-03-04 10:38:44.234994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90a8da5fc6a7"
down_revision = "950cac571497"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rounds", "months_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rounds", "months_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
