"""Created the relationship between prize and round.

Revision ID: 950cac571497
Revises: 2794a51430ed
Create Date: 2022-03-04 10:14:28.115974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "950cac571497"
down_revision = "2794a51430ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prizes", sa.Column("rounds_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "prizes", "rounds", ["rounds_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prizes", type_="foreignkey")
    op.drop_column("prizes", "rounds_id")
    # ### end Alembic commands ###
